FROM python:3.10-bullseye as build-stage


COPY Pipfile Pipfile.lock /tmp/

RUN python3 -m pip install pipenv \
    && PIPENV_PIPFILE=/tmp/Pipfile pipenv sync --system --dev

FROM python:3.10-slim-bullseye as app-stage

# ビルダーステージから、Pipenv でインストールしたライブラリをコピー
COPY --from=build-stage /usr/local/lib/python3.10/site-packages \
  /usr/local/lib/python3.10/site-packages
COPY --from=build-stage /usr/local/lib/python3.10/lib-dynload \
  /usr/local/lib/python3.10/lib-dynload
COPY --from=build-stage /usr/local/bin /usr/local/bin

COPY fast_api_sample /var/src/fast_api_sample
RUN chown -R nobody:nogroup /var/src && \
    chown -R nobody:nogroup /var/log

USER nobody

WORKDIR /var/src/fast_api_sample

EXPOSE 8080
CMD ["uvicorn", "fast_api_sample/main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
